data:
  root_path: "../RawData/"
  pickle_path: "../Data/vis_cortex_data.pickle"
  subjects: null
  shape_filter: null
  feature_type: "manhattan"
  train_size: 0.5
  n_chunks: 10
  frames_limit: 20000

model:
  model_type: "convlstm"
  num_classes: 3
  hidden_size: 64
  sequence_length: 64
  kernel_size: 3
  dropout_rate: 0.1

training:
  batch_size: 64
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "plateau"
  validation_split: 0.2
  early_stopping_patience: 10
  save_every: 10
  save_best: true

scheduler:
  mode: "min"
  factor: 0.5
  patience: 20
  min_lr: 0.0001
  verbose: true

# Paths
save_dir: "checkpoints"
log_dir: "logs"
results_dir: "results"

# Device
device: "auto"  # "auto", "cpu", "cuda"

# Random seed
seed: 42

# Logging
verbose: true
