# K-fold Cross-Validation Configuration for Visual Cortex Speckle Recognition

# Data Configuration
data:
  root_path: "../RawData/"
  pickle_path: "../Data/vis_cortex_data.pickle"
  subjects: null  # null means all subjects
  shape_filter: null  # null means all shapes
  feature_type: "manhattan"  # "manhattan", "euclidean", "ncc"
  train_size: 0.8  # Not used in K-fold, but kept for compatibility
  n_chunks: 10
  frames_limit: 20000

# Model Configuration
model:
  model_type: "convlstm"  # "convlstm", "conv1d", "enhanced_convlstm"
  num_classes: 3  # Will be set automatically based on data
  input_channels: 1
  num_filters: 64
  kernel_size: 3
  dropout_rate: 0.1
  
  # ConvLSTM specific parameters
  hidden_size: 64
  sequence_length: 64
  num_layers: 1

# Training Configuration
training:
  batch_size: 32
  epochs: 100  # Reduced for K-fold as each fold trains separately
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "plateau"
  validation_split: 0.0  # Not used in K-fold
  early_stopping_patience: 20  # Reduced for K-fold
  save_every: 25
  save_best: true
  
  # K-fold Cross-Validation Parameters
  use_kfold: true
  k_folds: 5
  kfold_stratified: true
  kfold_random_state: 42

# Scheduler Configuration
scheduler:
  mode: "min"
  factor: 0.5
  patience: 10
  min_lr: 0.0001
  verbose: true

# Paths
save_dir: "checkpoints"
log_dir: "logs"
results_dir: "results"

# Device
device: "auto"  # "auto", "cpu", "cuda"

# Random seed
seed: 42

# Logging
verbose: true
